Bundler/OrderedGems:
  Enabled: false

Layout/AlignArguments:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Rails/FilePath:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
